spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: rag
    password: ragpass
  flyway:
    enabled: true
    locations: classpath:db/migration

ingest:
  base-url: http://localhost:8001


